# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
permissions:
    id-token: write # This is required for requesting the JWT
    contents: read  # This is required for actions/checkout

name: Run in-toto tests, linter, install witness

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false
      # Run regular in-toto tests on each OS/Python combination, plus linters
      # on Linux/Python3.x only.
      matrix:
        python-version: ['3.7']
        os: [ubuntu-latest]
        toxenv: [py]
        include:
          - python-version: '3.x'
            os: ubuntu-latest
            toxenv: lint

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout in-toto
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'requirements*.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
          python -m pip install hatch

      - name: Run tox
        run: tox -e ${{ matrix.toxenv }}
        # use hatch to build the witness
      - name: witness hatch build
        uses: testifysec/witness-run-action@v0.1.3
        with:
          step: build
          enable-archivista: true
          enable-sigstore: true
          command: hatch build

      - name: Download witness policy tool
        uses: giantswarm/install-binary-action@v1.1.0
        with:
          binary: "policy-tool"
          version: "v0.3.0"
          download_url: "https://github.com/testifysec/${binary}/archive/refs/tags/${version}.tar.gz"
          tarball_binary_path: "*/src/policy-tool-0.3.0"