permissions:
    id-token: write # This is required for requesting the JWT
    contents: read  # This is required for actions/checkout
  
name: Example Workflow
on: [push, pull_request]
  
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
  
        - name: Witness Run
          uses: testifysec/witness-run-action@v0.1
          with:
            step: test
            use-archivista: false
            use-sigstore: false
            command: touch hello.txt